module WDW

include("Logic/DSL.jl")
include("Semantics/Kripke.jl")
include("Category/Sets.jl")
include("Knowledge/TopologicalFunctors.jl")
include("Sheaves/FiniteSheaves.jl")
include("Algebra/Quivers.jl")
include("Motives/ComputableMotives.jl")
include("Motives/MotivicReduce.jl")
include("Quantum/QGroupENN.jl")
include("Tensor/HolographicCodes.jl")
include("Krylov/Complexity.jl")
include("Time/ITE.jl")
include("Time/MultiTime.jl")
include("Time/HyperTime.jl")
include("Planner/ChronosKairos.jl")
include("Bio/Microtubules.jl")
include("Gravity/LQGDataSpace.jl")
include("Vacuum/QET.jl")
include("UnifiedWDW.jl")
include("RuptureABC.jl")
include("ScalableWDW.jl")
include("RealBaselines.jl")
include("RealWorldApplications.jl")
include("PaperMetrics.jl")
include("WDWAutoencoder.jl")
include("TheoreticalMetrics.jl")
include("RigorousMetrics.jl")
include("MultiDataset.jl")
include("LatticePhonons.jl")
include("BreakthroughExperiment.jl")
include("AutoSymmetryDiscovery.jl")
include("StructuralExperiments.jl")
include("FFTGroup.jl")
include("FFTPipeline.jl")
include("SymmetryDiscovery.jl")
include("SymmetryCertificate.jl")
include("UnifiedIntegration.jl")
include("StructuralEmbedding.jl")

include("AutoSymmetryFlux.jl")
include("mlp_baseline.jl")

export Logic, Semantics, Category, Knowledge, Sheaves, Algebra, Motives, MotivicReduce, Quantum, Tensor, Krylov, TimeITE, TimeMulti, TimeHyper, Planner, Bio, Gravity, Vacuum, UnifiedWDW, RuptureABC, ScalableWDW, RealBaselines, RealWorldApplications, PaperMetrics, WDWAutoencoder, TheoreticalMetrics, RigorousMetrics, MultiDataset, LatticePhonons, BreakthroughExperiment, AutoSymmetryDiscovery, StructuralExperiments, FFTGroup, FFTPipeline, SymmetryDiscovery, SymmetryCertificate, UnifiedIntegration, StructuralEmbedding

end
